# ASP.NET Core
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 5.0.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Webshop/Webshop/AngularApp/'

- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true